import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || ''
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || ''

if (!supabaseUrl || !supabaseAnonKey) {
  console.warn('⚠️ Supabase URL or Key is missing. Please check your .env.local file.')
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey)

// Database Types (will be auto-generated by Supabase later)
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          name: string
          role: 'teacher' | 'student'
          email: string | null
          password_hash: string | null
          access_token: string | null
          daily_goal: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          role: 'teacher' | 'student'
          email?: string | null
          password_hash?: string | null
          access_token?: string | null
          daily_goal?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          role?: 'teacher' | 'student'
          email?: string | null
          password_hash?: string | null
          access_token?: string | null
          daily_goal?: number
          created_at?: string
          updated_at?: string
        }
      }
      // 나머지 테이블 타입은 추후 추가
    }
  }
}

